INSERT INTO COUNTRY (CO_CODE, CO_NAME) VALUES ('IN', 'India');
INSERT INTO COUNTRY (CO_CODE, CO_NAME) VALUES ('US', 'United States');
INSERT INTO COUNTRY (CO_CODE, CO_NAME) VALUES ('JP', 'Japan');
INSERT INTO COUNTRY (CO_CODE, CO_NAME) VALUES ('AU', 'Australia');
INSERT INTO COUNTRY (CO_CODE, CO_NAME) VALUES ('ID', 'Indonesia');
INSERT INTO COUNTRY (CO_CODE, CO_NAME) VALUES ('BR', 'Brazil');
INSERT INTO COUNTRY (CO_CODE, CO_NAME) VALUES ('CA', 'Canada');